# Generated by Django 4.2.30 on 2026-05-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_roundrobinstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='score',
            field=models.IntegerField(default=0, help_text='Calidad del lead (0-100) basado en completitud de datos.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.IntegerField(default=0, help_text='Calidad del lead (0-100) basado en completitud de datos.'),
        ),
    ]
