# Generated by Django 4.2.30 on 2026-05-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_campaign_historicallead_utm_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='Déjanos tus datos y te contactaremos a la brevedad.')),
                ('primary_color', models.CharField(default='#3b82f6', help_text='Color HEX para el botón y detalles.', max_length=20)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages', to='leads.campaign')),
                ('source', models.ForeignKey(blank=True, help_text='Fuente asignada a los leads de esta landing.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.source')),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
