# Generated by Django 4.2.30 on 2026-05-07 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('email_sent', 'Email Enviado'), ('email_received', 'Email Recibido'), ('webhook', 'Webhook (Captura)'), ('note', 'Nota Manual'), ('status_change', 'Cambio de Estado'), ('system', 'Sistema')], db_index=True, default='webhook', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='raw_payload',
            field=models.JSONField(default=dict, help_text='Datos asociados al evento.'),
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Email Enviado',
                'verbose_name_plural': 'Emails Enviados',
                'ordering': ['-created_at'],
            },
        ),
    ]
