# Generated by Django 4.2.30 on 2026-05-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_interaction_type_alter_interaction_raw_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='benefit_1_icon',
            field=models.CharField(default='Building', help_text='Nombre del icono de Lucide (ej: Building, Zap, Shield)', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='benefit_1_title',
            field=models.CharField(default='Propiedades Exclusivas', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='benefit_2_icon',
            field=models.CharField(default='User', help_text='Nombre del icono de Lucide', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='benefit_2_title',
            field=models.CharField(default='Asesoría 1 a 1', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='benefit_3_icon',
            field=models.CharField(default='TrendingUp', help_text='Nombre del icono de Lucide', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='benefit_3_title',
            field=models.CharField(default='Alta Rentabilidad', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cta_text',
            field=models.CharField(default='Quiero más información →', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='success_message',
            field=models.TextField(default='¡Listo! Hemos recibido tu información. Uno de nuestros asesores se pondrá en contacto contigo a la brevedad.'),
        ),
    ]
