# Generated by Django 4.2.30 on 2026-05-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_landingpage_benefit_1_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brochure_description',
            field=models.TextField(blank=True, default='', help_text='Texto introductorio en el PDF.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='brochure_features',
            field=models.JSONField(blank=True, default=list, help_text="Lista de características destacadas para el PDF (ej: ['Piscina', 'Gimnasio'])."),
        ),
        migrations.AddField(
            model_name='campaign',
            name='brochure_title',
            field=models.CharField(blank=True, default='', help_text='Título principal en la portada del PDF.', max_length=200),
        ),
    ]
