# Generated by Django 4.2.30 on 2026-05-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_campaign_brochure_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.ImageField(upload_to='landings/media/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='benefit_1_icon',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='benefit_1_title',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='benefit_2_icon',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='benefit_2_title',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='benefit_3_icon',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='benefit_3_title',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='Lista modular de beneficios con icono y título.'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='form_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración dinámica de campos visibles y obligatorios.'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='visits_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LandingPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='leads.landingpage')),
            ],
        ),
        migrations.AddField(
            model_name='landingpage',
            name='image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_landings', to='leads.mediaasset'),
        ),
    ]
