# Generated by Django 4.2.30 on 2026-05-07 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0011_mediaasset_remove_landingpage_benefit_1_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta del Sistema',
                'verbose_name_plural': 'Alertas del Sistema',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='campaign',
            name='brochure_description',
            field=models.TextField(blank=True, default='', help_text='Breve introducción o descripción que aparecerá en el PDF.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='brochure_features',
            field=models.JSONField(blank=True, default=list, help_text="Lista de características (ej: ['Vista al mar', 'Seguridad 24/7'])."),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='brochure_title',
            field=models.CharField(blank=True, default='', help_text='Título principal en la portada del PDF generado automáticamente.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Vendedor responsable del cierre de este lead.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email de comunicación que el vendedor puede actualizar.', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='original_email',
            field=models.EmailField(db_index=True, help_text='Email de captura original. Inmutable. Se usa para unificar webhooks.', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='score',
            field=models.IntegerField(default=0, help_text='Calidad calculada del lead (0-100) según completitud de perfil.'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='raw_payload',
            field=models.JSONField(default=dict, help_text='Datos técnicos asociados al evento (JSON original).'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='Lista modular de beneficios con icono y título en formato JSON.'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='form_config',
            field=models.JSONField(blank=True, default=dict, help_text='Define qué campos pedir (teléfono, empresa, etc) y cuáles son obligatorios.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Vendedor responsable del cierre de este lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email de comunicación que el vendedor puede actualizar.', max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='original_email',
            field=models.EmailField(db_index=True, help_text='Email de captura original. Inmutable. Se usa para unificar webhooks.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='score',
            field=models.IntegerField(default=0, help_text='Calidad calculada del lead (0-100) según completitud de perfil.'),
        ),
        migrations.AlterField(
            model_name='roundrobinstate',
            name='last_assigned_user',
            field=models.ForeignKey(blank=True, help_text='El último vendedor al que se le asignó un lead automáticamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='edited_body',
            field=models.JSONField(blank=True, help_text='JSON editado manualmente para corregir errores de captura.', null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='raw_body',
            field=models.JSONField(help_text='Cuerpo JSON completo tal como fue recibido del servidor externo.'),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='source_type',
            field=models.CharField(help_text="Tipo de fuente reportado en el webhook (ej: 'facebook').", max_length=100),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitoso'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20),
        ),
    ]
