# Generated by Django 4.2.30 on 2026-05-08 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_systemalert_alter_campaign_brochure_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(help_text='Ej: Punta Cana, República Dominicana', max_length=255)),
                ('min_investment', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de inversión inicial.', max_digits=12)),
                ('estimated_return', models.CharField(blank=True, default='', help_text='Ej: 8% - 12% Anual', max_length=100)),
                ('delivery_date', models.CharField(blank=True, default='', help_text='Ej: Diciembre 2025', max_length=100)),
                ('amenities', models.JSONField(blank=True, default=list, help_text="Lista de amenidades (ej: ['Piscina', 'Playa privada']).")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_image', models.ForeignKey(blank=True, help_text='Imagen principal que aparecerá en el PDF.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='leads.mediaasset')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='properties',
            field=models.ManyToManyField(blank=True, help_text='Selecciona las propiedades que se mostrarán en el brochure de esta campaña.', related_name='campaigns', to='leads.property'),
        ),
    ]
