# Generated by Django 4.2.30 on 2026-05-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_landingpage_latitude_landingpage_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, help_text='Calle, Número, Oficina/Depto', max_length=255, null=True),
        ),
    ]
