# Generated by Django 4.2.30 on 2026-05-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interested_properties',
            field=models.ManyToManyField(blank=True, help_text='Proyectos específicos en los que el inversionista ha mostrado interés.', related_name='interested_leads', to='leads.property'),
        ),
    ]
