# Generated by Django 4.2.30 on 2026-05-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_lead_interested_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='investment_capacity',
            field=models.CharField(blank=True, default='', help_text='Rango de capital disponible para invertir.', max_length=100),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='investment_goal',
            field=models.CharField(blank=True, default='', help_text='Objetivo: Renta, Plusvalía o Patrimonio.', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='investment_capacity',
            field=models.CharField(blank=True, default='', help_text='Rango de capital disponible para invertir.', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='investment_goal',
            field=models.CharField(blank=True, default='', help_text='Objetivo: Renta, Plusvalía o Patrimonio.', max_length=100),
        ),
    ]
