# Generated by Django 4.2.30 on 2026-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_historicallead_investment_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='internal_notes',
            field=models.TextField(blank=True, default='', help_text='Notas internas del vendedor para seguimiento rápido.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='internal_notes',
            field=models.TextField(blank=True, default='', help_text='Notas internas del vendedor para seguimiento rápido.'),
        ),
    ]
