# Generated by Django 4.2.30 on 2026-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_historicallead_internal_notes_lead_internal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='contact_email',
            field=models.EmailField(blank=True, db_index=True, default='', help_text='Email de comunicación que el vendedor puede actualizar.', max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_email',
            field=models.EmailField(blank=True, db_index=True, default='', help_text='Email de comunicación que el vendedor puede actualizar.', max_length=254),
        ),
    ]
